### ISSUE TITLE
载入模块报错

### ISSUE THREAD

**Issue by Yamamoto-2** [Diving-Fish/mai-bot#12]
11-13 02:08:16 [INFO] nonebot | NoneBot is initializing...
11-13 02:08:16 [INFO] nonebot | Current Env: prod
11-13 02:08:16 [ERROR] nonebot | Failed to import "maimaidx"
Traceback (most recent call last):
  File "C:\mai-bot-main\bot.py", line 28, in <module>
    nonebot.load_plugins("src/plugins")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "src/plugins\maimaidx.py", line 9, in <module>
    from src.libraries.maimaidx_music import *
  File "C:\mai-bot-main\src\libraries\maimaidx_music.py", line 149, in <module>
    obj = requests.get('https://www.diving-fish.com/api/maimaidxprober/music_data').json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
11-13 02:08:16 [INFO] nonebot | Succeeded to import "public"
11-13 02:08:16 [INFO] nonebot | Running NoneBot...
11-13 02:08:16 [ERROR] nonebot | Failed to import "maimaidx"
Traceback (most recent call last):
  File "C:\mai-bot-main\bot.py", line 37, in <module>
    nonebot.run(app="bot:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 56, in serve
    config.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\mai-bot-main\bot.py", line 28, in <module>
    nonebot.load_plugins("src/plugins")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "src/plugins\maimaidx.py", line 9, in <module>
    from src.libraries.maimaidx_music import *
  File "C:\mai-bot-main\src\libraries\maimaidx_music.py", line 149, in <module>
    obj = requests.get('https://www.diving-fish.com/api/maimaidxprober/music_data').json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

11-13 02:08:17 [INFO] uvicorn | Started server process [7892]
11-13 02:08:17 [INFO] uvicorn | Waiting for application startup.
11-13 02:08:17 [INFO] uvicorn | Application startup complete.
11-13 02:08:17 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:10219 (Press CTRL+C to quit)

启动之后除了help以外所有功能都无法使用，确定没有任何代理，浏览器可以访问https://www.diving-fish.com/api/maimaidxprober/music_data 已经允许python.exe通过防火墙
windows10 LTSC python3.9.2
下载music_data.json 在src\libraries\maimaidx_music.py 第148行改为

with open("./music_data.json","r",encoding="utf-8")as josn_file_handle:
    obj=json.load(josn_file_handle) 

就可以正常运行了 不知道出了什么问题

**Comment by Diving-Fish** [comment]
ssl证书问题，get函数里添加一个verify=False的kw参数
