### ISSUE TITLE
网站Api倒了）

### ISSUE THREAD

**Issue by ShinokawaRaine** [Diving-Fish/mai-bot#4]
ERRLOG

08-31 15:52:15 [ERROR] nonebot | Failed to import "maimaidx"
Traceback (most recent call last):
  File "/root/mai-bot/bot.py", line 37, in <module>
    nonebot.run(app="bot:app")
  File "/root/mai-bot/lib/python3.9/site-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/root/mai-bot/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/root/mai-bot/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/root/mai-bot/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/root/mai-bot/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/root/mai-bot/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/mai-bot/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/mai-bot/bot.py", line 28, in <module>
    nonebot.load_plugins("src/plugins")
  File "/root/mai-bot/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/root/mai-bot/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/root/mai-bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/mai-bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/mai-bot/src/plugins/maimaidx.py", line 9, in <module>
    from src.libraries.maimaidx_music import *
  File "/root/mai-bot/src/libraries/maimaidx_music.py", line 149, in <module>
    obj = requests.get('https://www.diving-fish.com/api/maimaidxprober/music_data').json()
  File "/root/mai-bot/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShinokawaRaine** [comment]
Service Recovered, Closing the issue
