### ISSUE TITLE
b50报错

### ISSUE THREAD

**Issue by jiangyin14** [Diving-Fish/mai-bot#47]
```09-30 15:51:05 [SUCCESS] nonebot | ONEBOT V11 1923847080 | [message.group.normal]: Message 1313573342 from 1219439938@[群:708060292] "b50"
09-30 15:51:05 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False>
09-30 15:51:06 [INFO] nonebot | Matcher <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False> running complete
09-30 15:51:06 [ERROR] nonebot | Running matcher <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    nonebot.run()
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/py/lib/python3.8/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/py/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/py/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/py/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/py/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/py/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/local/py/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/py/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/mai/src/plugins/maimaidx.py", line 300, in _
    img, success = await generate50(payload)
  File "/root/mai/src/libraries/maimai_best_50.py", line 407, in generate50
    pic = DrawBest(sd_best, dx_best, obj["nickname"]).getDir()
  File "/root/mai/src/libraries/maimai_best_50.py", line 103, in __init__
    self.img = Image.open(self.pic_dir + 'UI_TTR_BG_Base_Plus.png').convert('RGBA')
  File "/usr/local/py/lib/python3.8/site-packages/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'src/static/mai/pic/UI_TTR_BG_Base_Plus.png'
```

**Comment by jiangyin14** [comment]
根据readme的step2第二段下载static文件夹之后报错修复 功能正常
