### ISSUE TITLE
定数查歌没法查定数中带“+”的歌

### ISSUE THREAD

**Issue by zhourenke** [Diving-Fish/mai-bot#52]
我的输入是：“## 定数查歌 12+”，命令前面的特殊符号是我自己设定的（但是我并不能看懂获取定数的那部分代码）
只要带着“+”就会出现这个
```
06-07 09:09:47 [SUCCESS] nonebot | ONEBOT V11 1145141919810 | [message.private.friend]: Message -2147483349 from 0189191415411 "## 定数查歌 12+"
06-07 09:09:47 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False>
06-07 09:09:47 [INFO] nonebot | Matcher <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False> running complete
06-07 09:09:47 [ERROR] nonebot | Running matcher <Matcher from src.plugins.maimaidx, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\zhour\mai-bot\bot.py", line 37, in <module>
    nonebot.run()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\zhour\scoop\apps\anaconda3\current\App\envs\mai-bot\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\zhour\mai-bot\src\plugins\maimaidx.py", line 51, in _
    result_set = inner_level_q(float(argv[0]))
ValueError: could not convert string to float: '12+'
```

**Comment by zhourenke** [comment]
解决了，不能输入“+”，要输入一个小数，如：“## 定数查歌 12.4”
