### ISSUE TITLE
载入模块时报错

### ISSUE THREAD

**Issue by sakuraikaede** [Diving-Fish/mai-bot#8]
报以下错误
```
09-17 23:13:57 [ERROR] nonebot | Failed to import "maimaidx"
Traceback (most recent call last):
  File "/home/kaede/dev-programs/mai-bot/bot.py", line 37, in <module>
    nonebot.run(app="bot:app")
  File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/home/kaede/.local/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/home/kaede/.local/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/home/kaede/.local/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/home/kaede/.local/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/kaede/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/kaede/dev-programs/mai-bot/bot.py", line 28, in <module>
    nonebot.load_plugins("src/plugins")
  File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 981, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 929, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/kaede/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 221, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/kaede/dev-programs/mai-bot/src/plugins/maimaidx.py", line 8, in <module>
    from src.libraries.tool import hash
ModuleNotFoundError: No module named 'src.libraries'
```
环境为 Arch Linux，Python 版本为 3.9.7

**Comment by Diving-Fish** [comment]
检查源码目录里面有没有 src/libraries/tool.py 文件

**Comment by sakuraikaede** [comment]
```
└── src
    ├── libraries
    │   ├── image.py
    │   ├── maimai_best_40.py
    │   ├── maimaidx_music.py
    │   └── tool.py
    └── plugins
        ├── maimaidx.py
        ├── public.py
```
存在的

**Comment by sakuraikaede** [comment]
上次 log 不完整
以下是完整 log
https://0bin.net/paste/Cz7XJRag#zO0si1ZBr5v+j6uzy-s5TLo39t7Fkl8vB7GQkOmHX/l

**Comment by Diving-Fish** [comment]
能否给一下使用的 nonebot 版本和 cqhttp 版本？

**Comment by sakuraikaede** [comment]
```
Name: nonebot2
Version: 2.0.0a8.post1
Summary: An asynchronous python bot framework.
Home-page: https://v2.nonebot.dev/
Author: yanyongyu
Author-email: yanyongyu_1@126.com
License: MIT
Location: /home/kaede/.local/lib/python3.9/site-packages
Requires: pygtrie, httpx, loguru, fastapi, pydantic, uvicorn
Required-by: nonebot-plugin-apscheduler, nonebot-adapter-cqhttp, nb-cli
```
go-cqhttp 版本为 v1.0.0-beta7-fix1

**Comment by Diving-Fish** [comment]
真有点不懂了……在别的平台或者系统上能成功运行吗？或者先运行一下nonebot2提供的小demo？

**Comment by sakuraikaede** [comment]
看起来是调用模块时的目录问题，我把 `from src.libraries.tool import hash` 改成 `from tool import hash` ，然后把 tool.py 移动到和 bot.py 相同的目录就没问题了
会不会是新版本 Python 更改了调用方式？
